[package]
name = "conditional_copy"
version = "0.1.0"
authors = ["Antonio Natilla <antonio.natilla@studenti.unimi.it>"]
edition = "2018"
license = "MIT"

[dependencies]
crossterm = "0.21.0"
clap = "2.33.3"